# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.box = "debian/bookworm64"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "sajansseS" do |sajansseS|

    sajansseS.vm.hostname = "sajansseS"
    sajansseS.vm.network "private_network", ip: "192.168.56.110"

    sajansseS.vm.provision "shell", inline: <<-SHELL
      if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
        ssh-keygen -t rsa -b 2048 -f /home/vagrant/.ssh/id_rsa -q -N ""
        cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys

        cp /home/vagrant/.ssh/id_rsa /vagrant/server_id_rsa
        cp /home/vagrant/.ssh/id_rsa.pub /vagrant/server_id_rsa.pub
      fi
    SHELL

    sajansseS.vm.provision "shell", path: "install_k3s_server.sh"
  end

  config.vm.define "hvincentSW" do |hvincentSW|
    hvincentSW.vm.hostname = "hvincentSW"
    hvincentSW.vm.network "private_network", ip: "192.168.56.111"

    hvincentSW.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh

      cat /vagrant/server_id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL

    hvincentSW.vm.provision "shell", path: "install_k3s_worker.sh"
  end

end
