# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

#NE PAS UTILISER LORS DE LA CORRECTION, IL FAUT TOUT FAIRE SUR UNE VRAIE VM (voir sujet)
Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.define "sajansseS" do |sajansseS|
    sajansseS.vm.hostname = "sajansseS"
    sajansseS.vm.network "private_network", ip: "192.168.56.110"
    sajansseS.vm.provision "shell", path: "scripts/install_dep.sh"
    sajansseS.vm.provision "shell", path: "scripts/install_k3d.sh"
    sajansseS.vm.provision "shell", path: "scripts/install_kubectl.sh"
    sajansseS.vm.provision "shell", path: "scripts/init_argocd.sh"
  end

end
